const CashLog = require('../models/CashLog');
const Order = require('../models/Order');
const Purchase = require('../models/Purchase');

const getCashLogs = async (req, res) => {
  try {
    const { month, year } = req.query;
    let dateFilter = {};

    if (month !== undefined && year !== undefined) {
      const m = parseInt(month);
      const y = parseInt(year);
      let startDate, endDate;
      if (m === 0) {
        startDate = new Date(y, 3, 1);
        endDate = new Date(y + 1, 2, 31, 23, 59, 59, 999);
      } else {
        const actualYear = m <= 3 ? y + 1 : y;
        startDate = new Date(actualYear, m - 1, 1);
        endDate = new Date(actualYear, m, 0, 23, 59, 59, 999);
      }
      dateFilter = { $gte: startDate, $lte: endDate };
    }

    // 1. Get manually added CashLog entries (non-sale, non-purchase originating)
    const manualLogsQuery = {
      companyId: req.user.companyId,
      ...(Object.keys(dateFilter).length ? { date: dateFilter } : {}),
      referenceId: { $exists: false } // Only manual entries without a linked order/purchase
    };
    const rawManualLogs = await CashLog.find(manualLogsQuery).sort({ date: -1 });
    const manualLogs = rawManualLogs.filter(l => l.paymentMode === 'Cash' || !l.paymentMode);

    // 2. Get ALL orders for the period
    const orderQuery = { companyId: req.user.companyId };
    if (Object.keys(dateFilter).length) orderQuery.date = dateFilter;
    const orders = await Order.find(orderQuery).sort({ date: -1 });

    // 3. Get all purchases for the period
    const purchaseQuery = { companyId: req.user.companyId };
    if (Object.keys(dateFilter).length) purchaseQuery.date = dateFilter;
    const purchases = await Purchase.find(purchaseQuery).populate('partyId', 'name').sort({ date: -1 });

    // Convert orders to CashLog-shaped entries (ONLY CASH, ONLY PAID AMOUNT)
    const orderLogs = orders
      .filter(o => o.paymentMode === 'Cash' || o.paymentMode === 'Split' || !o.paymentMode)
      .filter(o => (o.paymentMode === 'Split' ? o.paidCash > 0 : o.paidAmount > 0))
      .map(o => ({
        _id: `order_${o._id}`,
        type: 'IN',
        category: 'Sale',
        amount: o.paymentMode === 'Split' ? o.paidCash : o.paidAmount,
        description: o.customerName || 'Customer',
        paymentMode: 'Cash',
        date: o.date,
        createdAt: o.createdAt,
        isAutoGenerated: true,
        paymentStatus: o.paymentStatus
      }));

    // Convert purchases to CashLog-shaped entries (ONLY CASH/PAID OR SPLIT WITH CASH)
    const purchaseLogs = purchases
      .filter(p => p.status === 'Cash' || p.status === 'paid' || p.status === 'Paid' || (p.status === 'Split' && p.paidCash > 0))
      .map(p => {
        let amount = p.totalCost || p.cost || 0;
        if (p.status === 'Split') amount = p.paidCash;

        const vendorName = p.partyId ? p.partyId.name : (p.supplier || 'Vendor');
        const itemNames = p.items && p.items.length > 0 ? p.items.map(i => i.name).join(', ') : (p.item || 'Items');

        return {
          _id: `purchase_${p._id}`,
          type: 'OUT',
          category: 'Purchase',
          amount: amount,
          description: vendorName,
          paymentMode: 'Cash',
          date: p.date,
          createdAt: p.createdAt,
          isAutoGenerated: true
        };
      });

    // Combine all logs and sort by date descending
    let allLogs = [...manualLogs, ...orderLogs, ...purchaseLogs];

    // Calculate Opening Balance if startDate is present
    if (dateFilter.$gte) {
        const prevManualLogs = await CashLog.find({ companyId: req.user.companyId, date: { $lt: dateFilter.$gte }, referenceId: { $exists: false } });
        const filteredPrevManual = prevManualLogs.filter(l => l.paymentMode === 'Cash' || !l.paymentMode);
        
        const prevOrders = await Order.find({ companyId: req.user.companyId, date: { $lt: dateFilter.$gte } });
        const filteredPrevOrders = prevOrders
          .filter(o => o.paymentMode === 'Cash' || o.paymentMode === 'Split' || !o.paymentMode)
          .filter(o => (o.paymentMode === 'Split' ? o.paidCash > 0 : o.paidAmount > 0));
          
        const prevPurchases = await Purchase.find({ companyId: req.user.companyId, date: { $lt: dateFilter.$gte } });
        const filteredPrevPurchases = prevPurchases.filter(p => p.status === 'Cash' || p.status === 'paid' || p.status === 'Paid' || (p.status === 'Split' && p.paidCash > 0));

        let prevIn = 0;
        let prevOut = 0;
        
        filteredPrevManual.forEach(l => { if(l.type === 'IN') prevIn += l.amount; else prevOut += l.amount; });
        filteredPrevOrders.forEach(o => { prevIn += (o.paymentMode === 'Split' ? o.paidCash : o.paidAmount); });
        filteredPrevPurchases.forEach(p => { 
            let amt = p.totalCost || p.cost || 0; 
            if(p.status === 'Split') amt = p.paidCash; 
            prevOut += amt; 
        });

        const openingBalance = prevIn - prevOut;
        
        if (openingBalance !== 0) {
            allLogs.push({
                _id: 'auto_opening_balance',
                type: openingBalance > 0 ? 'IN' : 'OUT',
                category: 'OTHER',
                amount: Math.abs(openingBalance),
                description: 'Opening Balance (Carried Forward)',
                paymentMode: 'Cash',
                date: dateFilter.$gte,
                isAutoGenerated: true
            });
        }
    }

    allLogs.sort((a, b) => {
      const dateDiff = new Date(b.date).getTime() - new Date(a.date).getTime();
      if (dateDiff === 0) {
        const timeB = b.createdAt ? new Date(b.createdAt).getTime() : 0;
        const timeA = a.createdAt ? new Date(a.createdAt).getTime() : 0;
        return timeB - timeA;
      }
      return dateDiff;
    });

    // Calculate stats
    const totalIn = allLogs.filter(l => l.type === 'IN').reduce((acc, l) => acc + l.amount, 0);
    const totalOut = allLogs.filter(l => l.type === 'OUT').reduce((acc, l) => acc + l.amount, 0);

    res.json({
      logs: allLogs,
      stats: {
        totalIn,
        totalOut,
        balance: totalIn - totalOut
      }
    });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

const addCashLog = async (req, res) => {
  try {
    const newLog = new CashLog({
      ...req.body,
      companyId: req.user.companyId
    });
    await newLog.save();
    res.status(201).json(newLog);
  } catch (error) {
    res.status(400).json({ message: error.message });
  }
};

const deleteCashLog = async (req, res) => {
  try {
    await CashLog.findByIdAndDelete(req.params.id);
    res.json({ message: 'Log deleted' });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

const updateCashLog = async (req, res) => {
  try {
    const updatedLog = await CashLog.findByIdAndUpdate(req.params.id, req.body, { new: true });
    res.json(updatedLog);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

module.exports = {
  getCashLogs,
  addCashLog,
  deleteCashLog,
  updateCashLog
};
