const CashLog = require('../models/CashLog');
const Order = require('../models/Order');
const Purchase = require('../models/Purchase');

const getCashLogs = async (req, res) => {
  try {
    const { month, year } = req.query;
    let dateFilter = {};

    if (month !== undefined && year !== undefined) {
      const m = parseInt(month);
      const y = parseInt(year);
      let startDate, endDate;
      if (m === 0) {
        startDate = new Date(y, 3, 1);
        endDate = new Date(y + 1, 2, 31, 23, 59, 59, 999);
      } else {
        const actualYear = m <= 3 ? y + 1 : y;
        startDate = new Date(actualYear, m - 1, 1);
        endDate = new Date(actualYear, m, 0, 23, 59, 59, 999);
      }
      dateFilter = { $gte: startDate, $lte: endDate };
    }

    // 1. Get manually added CashLog entries (non-sale, non-purchase originating)
    const manualLogsQuery = {
      companyId: req.user.companyId,
      ...(Object.keys(dateFilter).length ? { date: dateFilter } : {}),
      referenceId: { $exists: false } // Only manual entries without a linked order/purchase
    };
    const rawManualLogs = await CashLog.find(manualLogsQuery).sort({ date: -1 });
    const manualLogs = rawManualLogs.filter(l => l.paymentMode === 'Cash' || !l.paymentMode);

    // 2. Get ALL orders for the period
    const orderQuery = { companyId: req.user.companyId };
    if (Object.keys(dateFilter).length) orderQuery.date = dateFilter;
    const orders = await Order.find(orderQuery).sort({ date: -1 });

    // 3. Get all purchases for the period
    const purchaseQuery = { companyId: req.user.companyId };
    if (Object.keys(dateFilter).length) purchaseQuery.date = dateFilter;
    const purchases = await Purchase.find(purchaseQuery).populate('partyId', 'name').sort({ date: -1 });

    // Convert orders to CashLog-shaped entries (ONLY CASH, ONLY PAID AMOUNT)
    const orderLogs = orders
      .filter(o => o.paymentMode === 'Cash' || !o.paymentMode)
      .filter(o => o.paidAmount > 0)
      .map(o => ({
        _id: `order_${o._id}`,
        type: 'IN',
        category: 'Sale',
        amount: o.paidAmount,
        description: `Sale to ${o.customerName}`,
        paymentMode: 'Cash',
        date: o.date,
        isAutoGenerated: true,
        paymentStatus: o.paymentStatus
      }));

    // Convert purchases to CashLog-shaped entries (ONLY CASH/PAID OR SPLIT WITH CASH)
    const purchaseLogs = purchases
      .filter(p => p.status === 'Cash' || p.status === 'paid' || p.status === 'Paid' || (p.status === 'Split' && p.paidCash > 0))
      .map(p => {
        let amount = p.totalCost || p.cost || 0;
        if (p.status === 'Split') amount = p.paidCash;

        const vendorName = p.partyId ? p.partyId.name : (p.supplier || 'Vendor');
        const itemNames = p.items && p.items.length > 0 ? p.items.map(i => i.name).join(', ') : (p.item || 'Items');

        return {
          _id: `purchase_${p._id}`,
          type: 'OUT',
          category: 'Purchase',
          amount: amount,
          description: `Purchase: ${itemNames} from ${vendorName}`,
          paymentMode: 'Cash',
          date: p.date,
          isAutoGenerated: true
        };
      });

    // Combine all logs and sort by date descending
    const allLogs = [...manualLogs, ...orderLogs, ...purchaseLogs].sort(
      (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()
    );

    // Calculate stats
    const totalIn = allLogs.filter(l => l.type === 'IN').reduce((acc, l) => acc + l.amount, 0);
    const totalOut = allLogs.filter(l => l.type === 'OUT').reduce((acc, l) => acc + l.amount, 0);

    res.json({
      logs: allLogs,
      stats: {
        totalIn,
        totalOut,
        balance: totalIn - totalOut
      }
    });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

const addCashLog = async (req, res) => {
  try {
    const newLog = new CashLog({
      ...req.body,
      companyId: req.user.companyId
    });
    await newLog.save();
    res.status(201).json(newLog);
  } catch (error) {
    res.status(400).json({ message: error.message });
  }
};

const deleteCashLog = async (req, res) => {
  try {
    await CashLog.findByIdAndDelete(req.params.id);
    res.json({ message: 'Log deleted' });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

module.exports = {
  getCashLogs,
  addCashLog,
  deleteCashLog
};
